<?php

/**
 * @file
 * Primary module hooks for Islandora Breadcrumbs module.
 */

use Drupal\node\NodeInterface;

/**
 * Implements hook_theme().
 */
function islandora_breadcrumbs_theme($existing, $type, $theme, $path) {
  return [
    'islandora_breadcrumb' => [
      'variables' => [
        'links' => [],
      ],
    ],
  ];
}

/**
 * Prepares variables for breadcrumb templates.
 *
 * Adapted from theme.inc/template_preprocess_breadcrumb.
 *
 * @param array $variables
 *   An associative array containing:
 *   - links: A list of \Drupal\Core\Link objects which should be rendered.
 */
function islandora_breadcrumbs_preprocess_islandora_breadcrumb(array &$variables) {
  $node = \Drupal::routeMatch()->getParameter('node');
  if ($node instanceof NodeInterface) {
    $type = $node->getType();
    if ($type == "islandora_object") {
      $variables['breadcrumb'] = [];
      /** @var \Drupal\Core\Link $link */
      foreach ($variables['links'] as $key => $links) {
        foreach ($links as $link) {
          $variables['breadcrumb'][$key][] = [
            'text' => $link->getText(),
            'url' => $link->getUrl()->toString(),
          ];
        }
      }
    }
  }
}
